* archives de l'Ain
** Courtes
*** Registre des Actes de Mariages
**** 1886
***** p2: mariage Raffin Louis Claude / Bertilles Marie Virginie
      http://www.archives.ain.fr/archives/visu/144336/1/daogrp/0/layout:table/idsearch:RECH_16e7c964b46dd62a9736045259dbe8bc#id:204165653
****** Texte
        (en marge) : mariage Raffin Louis Claude (célibataire) ET
        Bertillet Marie Virginie (célibataire)

	L'an mil huit cent quatre-vingt-six, et le neuf du mois de
	septembre à sept heures du soir par-devant nous Duthion Jean
	Baptiste remplissant en qualité de Maire les fonctions
	d'Officier de l’État civil de la commune de Courtes, canton
	de Saint Trivier de Courtes département de l'Ain, sont
	comparus en la maison commune

	Raffin Louis Claude, célibataire, profession de cultivateur
	demaurant à Courtes canton de Saint Trivier de Courtes,
	département de l'Ain, âgé de vingt-six ans, né à Curciat
	Dongalon le dix février mil huit cent soixante, fils majeur de
	défunt Raffin Pierre Marie quand vivait, profession de
	cultivateur, demeurant à Lescheroux et de Coulon Marie Louise
	profession de cultivatrice demeurant à Saint Nizier le
	Bouchoux procédant comme majeur et du consentement de sa mère
	ici présente d'une part ;

	Et Mademoiselle Bertillet Marie Virginie, célibataire,
	profession de cultivatrice, demeurant à Courtes, canton de
	Saint Trivier de Courtes, département de l'Ain, âgée de
	vingt-deux ans, née à Varennes Saint Sauveur, Saône et Loire,
	le neuf février mil huit cent soixante-quatre, fille majeure
	de Bertillet Claude Joseph quand vivait, profession de
	cultivateur, demeurant à Curciat Dongalon et de défunte
	Delorme Marie Benoîte quand vivait, profession de
	cultivatrice demeurant à Courtes, procédant comme majeure et
	maîtresse de ses droits d'autre part ;

	Lesquels  après nous avoir fait remise, savoir, le futur
	époux de son acte de naissance relaté plus haut, de l'acte de
	décès de son père, dressé à la mairie de Lescheroux le six
	octobre mil huit cent soixante-neuf

	et la future épouse de son acte de naissance relaté plus haut,
	de l'acte de décès de son père dressé à la mairie de Curciat
	Dongalon le dix-neuf juin mil huit cent septante huit, de l'acte
	de décès de sa mère dressé à la mairie de Courtes, la future
	épouse déclare à serment qu'elle ignore le lieu du décès de
	ses grands père, paternels et maternels. Ses témoins font
	également la même déclaration

	nous ont requis de procéder à la célébration du mariage
	projeté entre eux et dont les publications et affiches ont été
	faites à Courtes les deux dimanches consécutifs vingt-neuf
	Août et cinq Septembre courant conformément aux articles 63 et
	64 du Code civil, sans qu'aucune opposition à ce mariage nous
	ait été signifiée. Sur quoi nous avons interpellé les futurs
	époux ainsi que les personnes autorisant le mariage et
	présentes à l'acte, d'avoir à déclarer s'il a été fait un
	contrat de mariage ; à quoi il nous a été répondu
	affirmativement que le dit contrat a été reçu par Mte Pariset
	notaire à Curciat Dongalon le vingt-huit Août mil huit cent
	quatre-vingt-six.

	Puis, faisant droit à leur réquisition, après avoir fait
	lecture aux parties et aux témoins ci-nommés de toutes les
	pièces ci-dessus mentionnées et du chapitre 6, titre 5, du
	Code civil, intitulé *Du Mariage*, nous avons demandé au futur
	époux et à la future épouse s'ils veulent se prendre pour mari
	et femme ; et chacun d'eux ayant répondu affirmativement, nous
	déclarons *Au nom de la Loi que Raffin Louis Claude et
	Bertillet Marie Virginie sont unis par le mariage*.

	Et sur-le-champ nous avons dressé acte de mariage célébré
	publiquement et en présence de
	* 1° Rongier Emile âgé de vingt-huit ans, profession de
          Instituteur demeurant à Courtes, ami des époux ;
	* 2° Brochand François âgé de vingt-quatre ans, profession de
          cultivateur demeurant à Courtes, ami des époux ;
	* 3° Pernet Camille âgé de trente-six ans, profession de
          cultivateur demeurant à Courtes, ami des époux ;
	* 4° Sarron Pierre Constantin âgé de quarante un ans,
          profession de cultivateur demeurant à Courtes, ami des
          époux.

	Duquel acte, inscrit sur les deux registres tenus à cet effet,
	nous avons fait lecture aux témoins et aux parties
	contractantes qui ont signé avec nous à l'exception de
	l'épouse et de la mère de l'époux qui requises de le faire ont
	déclaré ne le savoir.

	Raffin   Sarron   Perrot    Brochand     Rongier     Duthion 

** Curciat-Dongalon
*** Registre des déclarations de Naissances
**** 1859
***** p16, page de gauche, haut et bas
      http://www.archives.ain.fr/ark:/22231/vta831a8a60d334f4a4/daogrp/0/layout:table/idsearch:RECH_bec83edfaf50682d9d7c9714edb3df63#id:1168284247
****** Texte
       (en marge) : N°5 NAISSANCE de Raffin Marie Josephte

       L'an mil huit cent soixante, et le onze du mois de février à
       onze heures du matin par-devant nous Pariset Joseph remplissant
       en qualité de Maire les fonctions d'Officier de l'état civil de
       la commune de Curciat Dongalon de Saint Trivier de Courtes,
       département de l'Ain, a comparu Raffin Pierre Marie âgé de
       quarante [cinq] ans profession de cultivateur domicilié à
       Curciat Dongalon, lequel nous a présenté un enfant du sexe
       féminin né en cette commune au domicile du déclarant au
       montalapiat le jour d'hier à deux heures du soir, fille de lui
       déclarant et de Coulon Marie Louise, son épouse âgée de trente
       huit ans, cultivatrice domiciliée au même lieu et auquel il a
       été déclaré donner les prénoms de Marie Josephte.

       Ces déclaration et présentation faites en présence de 1° Sarron
       Joseph âgé de quarante sept ans, profession de cultivateur,
       domicilié à Curciat Dongalon 2° Tréboz Jean Claude âgé de
       quarante trois ans, profession de boucher, domicilié au même
       lieu. De quoi nous avons dressé et inscrit de suite sur les
       deux registres tenus à cet effet le présent acte de naissance,
       dont nous avons fait lecture au comparant et aux témoins qui
       n'ont signé avec nous pour ne savoir : de ce par nous requis.

       Pariset

       (en marge)   N°6   NAISSANCE de Raffin Louis Claude -

       L'an mil huit cent soixante et le onze de mois de février à
       onze heures du matin par-devant nous Pariset Joseph remplissant
       en qualité de maire les fonctions d' Officier de l'état civil
       de la commune de Curciat Dongalon de Saint Trivier de Courtes,
       département de l'Ain, a comparu Raffin Pierre Marie âgé de
       quarante [huit] ans profession de cultivateur domicilié à
       Curciat Dongalon lequel nous a présenté un Enfant de sexe
       masculin né en cette commune au domicile du déclarant au
       montalapiat le jour d'hier à trois heures du soir, fils de lui
       déclarant et de Coulon Marie Louise son épouse âgée de trente
       huit ans, cultivatrice domiciliée au même lieu et auquel il a
       été déclaré donner les prénoms de Louis Claude.

       Ces déclaration et présentation faites en présence de 1° Sarron
       Joseph âgé de de quarante sept ans, profession de cultivateur
       domicilié à Curciat Dongalon, 2° Tréboz Jean Claude âgé de
       quarante trois ans, profession de boucher, domicilié au même
       lieu. De quoi nous avons dressé et inscrit de suite sur les
       deux registres tenus à cet effet le présent acte de naissance
       dont nous avons fait lecture au comparant et aux témoins qui
       n'ont signé avec nous pour ne savoir : de ce par nous requis.

       Pariset

** Lescheroux
*** Registre des Actes de Décès
**** 1866-1869
***** p41, page de droite, haut, (décès n° 19)
      http://www.archives.ain.fr/ark:/22231/vtad2a238eb70b581ad/daogrp/0/layout:table/idsearch:RECH_04baedae09f2040e7678310ee245e20c#id:2051620033
****** Texte
       (en marge :) N°19 . Décès Raffin Pierre Marie. 5 Octobre 1869


       L'an mil huit cent soixante neuf, et le six du mois d'octobre à
       dix heures du matin par-devant nous Bereiziat Joseph Marie
       remplissant en qualité de Maire les fonctions d'Officier de
       l'état civil de la commune de Lescheroux canton de Saint
       Trivier de Courtes département de l'Ain, ont comparu

       1° Raffin Pierre Victor âgé de vingt sept ans, profession de
       cultivateur domicilié à Courtes, fils du décédé ;

       2° Pitre Joseph âgé de quarante sept ans, profession de
       cultivateur domicilié à Lescheroux, voisin du décédé ;

       lesquels nous ont déclaré que Raffin Pierre Marie époux de
       Colomb Luce, âgée de quarante huit ans, âgé de cinquante cinq
       ans, profession de cultivateur, domicilié à Lescheroux, né à
       Saint Nizier le Bouchoux, fils de Raffin Louis décédé à Saint
       Trivier de Courtes et de Bellevret Marie Josephte décédée à
       Bourg, est décédé en cette commune et au domicile de lui-même,
       hameau du Petit Villaret le jour d'hier, cinq du mois d'octobre
       à cinq heures du soir ainsi que nous nous en sommes assuré.

       Et sur-le-champ nous avons dressé et inscrit sur les deux
       registres tenus à cet effet le présent Acte de décès, dont nous
       avons fait lecture aux déclarants qui ont signé avec nous à
       l'exception du second déclarant, pour ne le savoir, de ce par
       nous requis.
       
       Raffin                                               Bereiziat

** Saint-Nizier-le-Bouchoux
*** Registres des Actes de Baptêmes, Mariages & Sépultures
**** 1765-1766
***** p12, page de droite, centre (mariage)
      http://www.archives.ain.fr/ark:/22231/vta6053f431c2674eb6/daogrp/0/layout:table/idsearch:RECH_59a3599fe08eea3dc07b7cd341a6d789#id:1424282891
****** Texte
       Mariage

       Le second juillet mil sept cent soixante cinq, Claude-Joseph
       Raffin, fils de feu Claude Raffin et de Marie Filliardet mariés
       paravant de l'autorité de la fille filliavet pas mire tous deux
       labos autellea paroisse de Curciat père la cremiese en date du
       1 juillet 1764 signé couroy curé après les trois publication
       faites suivant l'usage de l'église sans aucun empêchement a
       reçu par moi sous signé la bénédiction nuptiale dans l'église
       du saint lieu

       avec Marie Gadollet fille de Pierre Gadollet et de feu Claudine
       Gras mariés paravant de l'autorité de feu gavotte son père
       Louis Gras de labeur au pelio maloigna paroisse de St Nizier par
       acte xxx nous le 13 juin xxx et ce en présence de Claude Joseph
       Filliardet cousin germain de l'époux Pierre Gadollet père de
       l'épouse, Antoine Billet beaufrère de l'époux François Gras
       oncle de l'épouse Marie Filliardet mère de l'époux lesquels sont 
       XXX de ce enquis.

       Pegeffe

****** Autres sources à creuser :
       http://gw.geneanet.org/kifrifard?lang=en&v=GADOLLET&m=N
	- Claude 1688- &1713 Angélique ARBEZ 1693-1748
	  - Claude 1714- &1739 Jeanne RAFFIN 1719-
	    - Jeanne-Marie 1760- &1780 Pierre, Maurice PERRIN 1758-1826
	  - Pierre 1716-1785 &1741 Claudine GRAS 1711-
	    - Marie-Anne 1742-1807 &1762 Antoine BILLET 1737-
	    - Marie 1745- &1765 Claude-Joseph RAFFIN 1740-
	  - Claudine 1718- &1738 Jacques BILLET 1713-

       http://gw.geneanet.org/ppacaud?lang=en&pz=pierre&nz=pacaud&ocz=0&m=A&p=claude+joseph&n=raffin&siblings=on&notes=on&t=T&v=6&image=on&marriage=on&full=on

**** 1771-1772
***** p2, page de droite, centre (baptême)
      http://www.archives.ain.fr/ark:/22231/vtae720fd0594f6d68b/daogrp/0/layout:table/idsearch:RECH_b344cf2162adadb0a0fa91c77bc00b95#id:314368244
****** Texte
       Bap

       Louis fils de Claude Joseph Raffin laboureur au Grand Malorgnia
       de St Nizier et de Marie Gadollet mariés est né et a été
       baptisé le vingt six janvier nil sept cent soixante et onze par
       moi sous signé. Son parrain a été Louis tvondire laboureur a
       LuiMéal et la marraine Jeanne Marie Favour du dit Malvignia qui
       ont déclaré ne scavoir signé de ce enquis. C reyeffenve

*** Registre des Actes de Décès
**** 1817
***** p4, page de droite, haut
      http://www.archives.ain.fr/ark:/22231/vtab646e49f4ae699a4/daogrp/0/layout:table/idsearch:RECH_4a2e4ec07fbf6c6714edf1c229c74a3a#id:1221311453
****** Texte

       (en marge) décès de louis alexandre raffin

       L'an mil huit cent dix-sept et le dix-sept du mois d'avril
       pardevant nous antoine vélon maire Officier de l'état civil de
       la commune de Saint nizier le Bouchoux département de l'Ain,
       canton de Saint Trivier de Courtes sont comparus Denis moine et
       Claude marie Claire tous deux cultivateurs demaurant audit lieu
       de mépillat dite commune de Saint nizier le Bouchoux lesquels
       nous ont déclaré que louis alexandre Raffin, fils de louis
       Raffin et de marie josephte Belevrait journailliers demaurant à
       Béraude dite commune de Saint nizier le Bouchoux est décédé le
       six du mois d'avril à dix heures du matin.

       Nous avons signé le présent acte de décès dont nous avons donné
       lecture aux déclarans qui ont déclaré ne savoir signer de ce
       enquis.

       Vélon
       maire 

**** 1839
***** p12, page de gauche, haut
      http://www.archives.ain.fr/ark:/22231/vtae3bf55dcf6c3862a/daogrp/0/layout:table/idsearch:RECH_64ab2cdf940f6f68049876dfd9187d91#id:483616192
****** Texte

       (en marge) DECES de Raffin Marie morte-née

       L'an mil huit cent trente-neuf et le quatorze du mois d'octobre
       à quatre heures du soir par-devant nous Vélon Pierre joseph dit
       Lyonnais remplissant en qualité de maire les fonctions
       d'Officier de l'état civil de la commune de St Nizier le
       Bouchoux canton de St trivier de Courtes département de l'Ain,
       sont comparus Daniel Raffin âgé de trente quatre ans,
       profession de cultivateur, domicilié à St Nizier le Bx père de
       la décédée ; et Daniel Billoud âgé de vingt-six ans,
       profession de Maréchal Fe domicilié à St Nizier le Bx, voisin
       de la décédée lesquels nous ont déclaré que Raffin Marie sans
       âge et sans profession domiciliée à St Nizier, fille de Denis
       Raffin et de Claudine Pagneux est décédée en cette commune, et
       au domicile de ses père et mère le treize du mois d'octobre à
       deux heures du soir, ainsi que nous nous en sommes assuré.

       Et sur-le-champ nous avons dressé et inscrit sur les deux
       registres tenus à cet effet le présent Acte de décès, dont
       nous avons fait lecture aux déclarans qui n'ont signé avec nous
       pour ne savoir, de ce par nous requis.

                                                             Le Maire
                                                               Vélon


**** 1841
***** p10, page de gauche, haut et bas
      http://www.archives.ain.fr/ark:/22231/vta8d965e465b223464/daogrp/0/layout:table/idsearch:RECH_2c1914d1b890a26b040d0ae3c571eead#id:1196848674
**** 1857
***** p3, page de gauche, haut
      http://www.archives.ain.fr/ark:/22231/vta62fe1c32d7fbc47a/daogrp/0/layout:table/idsearch:RECH_d67d5ef1fae48980f4e7b5e96e195882#id:1492301090
**** 1858
***** p5, page de droite, haut
      http://www.archives.ain.fr/ark:/22231/vtae4c6f94da299a079/daogrp/0/layout:table/idsearch:RECH_8b0156bb99f42ea82b8747e08ad9de73#id:1566638588
*** Registre des Actes de Mariages
**** 1804-1805
***** p2, page de gauche
      http://www.archives.ain.fr/ark:/22231/vta368bcc948fbcdeec/daogrp/0/layout:table/idsearch:RECH_a27dc355ca253cf402c4847fe8092c04#id:2056314227
**** 1839
***** p19
      http://www.archives.ain.fr/ark:/22231/vtafd5e30418e3b9c51/daogrp/0/layout:table/idsearch:RECH_34daddf8c7922f80fcafe92e5b06c319#id:1512947111
**** 1877
***** p14
      http://www.archives.ain.fr/ark:/22231/vtafe032c65ea3ab3db/daogrp/0/layout:table/idsearch:RECH_d5bcd0c06391d0e40fe2e59afb29c4e1#id:1271389804
**** 1889
***** p3
      http://www.archives.ain.fr/ark:/22231/vtad5b8d3e12d5e0a82/daogrp/0#id:772310868
*** Registre des déclarations de Naissances
**** 1812
***** p8, page de gauche, bas
      http://www.archives.ain.fr/ark:/22231/vtaedd098eb270b0dc4/daogrp/0/layout:table/idsearch:RECH_8576dac399b1668a5776e684c11e609a#id:1978609445
**** 1814
***** p17, page de droite, haut
      http://www.archives.ain.fr/ark:/22231/vta459f28d9acc6b262/daogrp/0/layout:table/idsearch:RECH_f87fb32fb2f12b7e2b0db28ad7dc66b8#id:517457337
**** 1822
***** p14, page de droite, haut (naissance de Luce Coulon)
      http://www.archives.ain.fr/ark:/22231/vta8fec084f04473a54/daogrp/0/layout:table/idsearch:RECH_a78bae40bf5108fe51964da44c8627d7#id:1946185110
**** 1836
***** p14, page de gauche, bas
      http://www.archives.ain.fr/ark:/22231/vtad90f23c358d63757/daogrp/0/layout:table/idsearch:RECH_3c63cef457c594c4e6f3f9a713037999#id:2102134986
**** 1837
***** p12, page de droite, haut
      http://www.archives.ain.fr/ark:/22231/vtaa527fea8c2fa9224/daogrp/0/layout:table/idsearch:RECH_6a8852f1f6086d74c52f638e59966f02#id:869801452
**** 1838
***** p6, page de droite, bas
      http://www.archives.ain.fr/ark:/22231/vta892752d9bd598de3/daogrp/0/layout:table/idsearch:RECH_360f03c9daca43998f19123988a155af#id:339444057
**** 1839
***** p2, page de droite, bas
      http://www.archives.ain.fr/ark:/22231/vtaabd7ff1b7eadf1dd/daogrp/0/layout:table/idsearch:RECH_64ab2cdf940f6f68049876dfd9187d91#id:1569930549
**** 1840
***** p7, page de droite, bas
      http://www.archives.ain.fr/ark:/22231/vta08e77aaa0de44412/daogrp/0/layout:table/idsearch:RECH_f25734bdffa3de0a46edf1857c1483b5#id:1338250246
***** p12, page de droite, bas
      http://www.archives.ain.fr/ark:/22231/vta08e77aaa0de44412/daogrp/0/layout:table/idsearch:RECH_f25734bdffa3de0a46edf1857c1483b5#id:1314238700
**** 1842
***** p4, page de droite, bas
      http://www.archives.ain.fr/ark:/22231/vta8317dacf2329556c/daogrp/0/layout:table/idsearch:RECH_03d75a321a837cce2ba9797f5469b40a#id:1127340343
***** p17, page de droite, bas
      http://www.archives.ain.fr/ark:/22231/vta8317dacf2329556c/daogrp/0/layout:table/idsearch:RECH_03d75a321a837cce2ba9797f5469b40a#id:1158740057
***** p18, page de gauche, hait (suite du précédent)
      http://www.archives.ain.fr/ark:/22231/vta8317dacf2329556c/daogrp/0/layout:table/idsearch:RECH_03d75a321a837cce2ba9797f5469b40a#id:1159663578
**** 1843
***** p14, page de gauche, haut
      http://www.archives.ain.fr/ark:/22231/vta7c19471d337edf5a/daogrp/0/layout:table/idsearch:RECH_ff66e7cb0c3e3f704174233e0491eb5f#id:1904817226
**** 1850
***** p6, page de gauche, bas
      http://www.archives.ain.fr/ark:/22231/vta7e36ae3f16eee066/daogrp/0/layout:table/idsearch:RECH_1259265427341589c31b183cf78082e6#id:1734281575
**** 1852
***** p8, page de droite, bas
      http://www.archives.ain.fr/ark:/22231/vta4fe3aa5979f8cdf3/daogrp/0/layout:table/idsearch:RECH_86a8b57dca848ed290378427a3444f64#id:735926619
**** 1856
***** p15, page de gauche, haut
      http://www.archives.ain.fr/ark:/22231/vtac5033c6611df3c9d/daogrp/0/layout:table/idsearch:RECH_84757bb9994563dadb645653f44a4e14#id:1403540215
**** 1890
***** p1, page de gauche, bas
      http://www.archives.ain.fr/ark:/22231/vta7c47ad08dcf65cb2/daogrp/0/layout:table/idsearch:RECH_4ab3a712446c0c06f8856ed0fa4e5818#id:975636884
** Vernoux
*** Registre des déclarations de Naissances
**** 1887
***** p6, page de droite, bas
      http://www.archives.ain.fr/ark:/22231/vta8dd0d56f95372a1d/daogrp/0/layout:table/idsearch:RECH_6c3be1cece959e4661bf8480613af090#id:1064823185
**** 1889
***** p2, page de gauche, bas
      http://www.archives.ain.fr/ark:/22231/vta0fdebbe379fd1a75/daogrp/0/layout:table/idsearch:RECH_b9b58bf82c6abfcbfb41391b9a8b94cf#id:38819038
**** 1891
***** p16, page de gauche, haut
      http://www.archives.ain.fr/ark:/22231/vta0fdebbe379fd1a75/daogrp/0/layout:table/idsearch:RECH_b9b58bf82c6abfcbfb41391b9a8b94cf#id:6495803
